sudo: required
language: java
jdk:
- openjdk8
before_script:
- wget https://services.gradle.org/distributions/gradle-6.0-bin.zip
- unzip gradle-6.0-bin.zip
- export GRADLE_HOME=$PWD/gradle-6.0
- export PATH=$GRADLE_HOME/bin:$PATH
addons:
  sonarcloud:
    organization: api-testing-01
    token:
      secure: "$SONAR_TOKEN"
script:
- gradle compileJava compileTestJava
- sonar-scanner
- gradle check
- gradle clean runFeatures
notifications:
  email: true
before_install:
- openssl aes-256-cbc -K $encrypted_7ea55fc27151_key -iv $encrypted_7ea55fc27151_iv
  -in config.json.enc -out config.json -d
